name = "noroshi-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]

# Cron Triggers for automatic task reminders
[triggers]
crons = [
  "5 13 * * 1-5",   # 10:05 PM JST (13:05 UTC) - 夜のタスク状況1
  "15 13 * * 1-5",  # 10:15 PM JST (13:15 UTC) - 夜のタスク状況2
  "25 13 * * 1-5",  # 10:25 PM JST (13:25 UTC) - 夜のタスク状況3
  "35 13 * * 1-5",  # 10:35 PM JST (13:35 UTC) - 夜のタスク状況4
  "45 13 * * 1-5"   # 10:45 PM JST (13:45 UTC) - 夜のタスク状況5
]

[env.production]
name = "noroshi-mcp-server"

[env.staging]
name = "noroshi-mcp-server-staging"

# Environment variables (set via wrangler secret)
# SLACK_BOT_TOKEN
# SLACK_APP_TOKEN  
# SLACK_TEAM_ID 