name = "noroshi-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]

# Cron Triggers for automatic task reminders
[triggers]
crons = [
  "15 14 * * 1-5",  # 11:15 PM JST (14:15 UTC) - 夜のタスク状況1
  "25 14 * * 1-5",  # 11:25 PM JST (14:25 UTC) - 夜のタスク状況2
  "35 14 * * 1-5",  # 11:35 PM JST (14:35 UTC) - 夜のタスク状況3
  "45 14 * * 1-5",  # 11:45 PM JST (14:45 UTC) - 夜のタスク状況4
  "55 14 * * 1-5"   # 11:55 PM JST (14:55 UTC) - 夜のタスク状況5
]

[env.production]
name = "noroshi-mcp-server"

[env.staging]
name = "noroshi-mcp-server-staging"

# Environment variables (set via wrangler secret)
# SLACK_BOT_TOKEN
# SLACK_APP_TOKEN  
# SLACK_TEAM_ID 