name = "noroshi-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]

# Cron Triggers for automatic task reminders
[triggers]
crons = [
  "20 12 * * 1-5",  # 9:20 PM JST (12:20 UTC) - 夜のタスク状況1
  "30 12 * * 1-5",  # 9:30 PM JST (12:30 UTC) - 夜のタスク状況2
  "40 12 * * 1-5",  # 9:40 PM JST (12:40 UTC) - 夜のタスク状況3
  "50 12 * * 1-5",  # 9:50 PM JST (12:50 UTC) - 夜のタスク状況4
  "0 13 * * 1-5"    # 10:00 PM JST (13:00 UTC) - 夜のタスク状況5
]

[env.production]
name = "noroshi-mcp-server"

[env.staging]
name = "noroshi-mcp-server-staging"

# Environment variables (set via wrangler secret)
# SLACK_BOT_TOKEN
# SLACK_APP_TOKEN  
# SLACK_TEAM_ID 