name = "noroshi-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]

# Cron Triggers for automatic task reminders
[[triggers]]
crons = [
  "0 0 * * 1-5",   # 9:00 AM JST (0:00 UTC) - 朝のタスク状況
  "0 4 * * 1-5",   # 1:00 PM JST (4:00 UTC) - 昼のタスク状況  
  "30 6 * * 1-5",  # 3:30 PM JST (6:30 UTC) - 午後のタスク状況
  "0 8 * * 1-5",   # 5:00 PM JST (8:00 UTC) - 夕方のタスク状況
  "0 12 * * 1-5"   # 9:00 PM JST (12:00 UTC) - 夜のタスク状況
]

[env.production]
name = "noroshi-mcp-server"

[env.staging]
name = "noroshi-mcp-server-staging"

# Environment variables (set via wrangler secret)
# SLACK_BOT_TOKEN
# SLACK_APP_TOKEN  
# SLACK_TEAM_ID 